-- clear the commandline 
cl scr

-- Create  TABLESPACE 

CREATE [TEMPORARY | UNDO] TABLESPACE "nome_tablespace"
DATAFILE "caminho\nome_datafile" SIZE tamanho
[AUTOEXTEND ON NEXT tamanho MAXSIZE tamanho [UNLIMITED]]
[ONLINE | OFFLINE]

-- Exemplo:
CREATE TABLESPACE ABC
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\Abc.dbf'
SIZE 10M 
AUTOEXTEND ON NEXT 1M MAXSIZE 100M;

-- List tablespace in Oracle databases

SELECT TABLESPACE_NAME from DBA_TABLESPACES;

-- Structure of  the  DBA_TABLESPACES;

DESC DBA_TABLESPACES;

-- Modify the size of Abc tablespace.
-- Syntax

ALTER DATABASE DATAFILE "name_datafile"
RESIZE  size_datafile

-- Example
ALTER DATABASE DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\Abc.dbf'
RESIZE 15M;


-- DROP The TABLESPACE

DROP TABLESPACE "name_tablespace" [INCLUDING CONTENTS [AND | KEEP] DATAFILES] [CASCADE CONSTRAINTS];

-- Example
DROP TABLESPACE ABC INCLUDING CONTENTS AND DATAFILES;


-- See the tablespace status

Syntax:

ALTER TABLESPACE "name_tablespace" [ONLINE | OFFLINE]

-- Example

--TABLESPACE
ALTER TABLESPACE 'ABC' OFFLINE;

SELECT TABLESPACE_NAME, STATUS FROM DBA_TABLESPACES;

















DROP TABLESPACE "2M_828507";
DROP TABLESPACE "2M_828507" INCLUDING CONTENTS;
DROP TABLESPACE "2M_828507" INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP DATAFILE "2M_828507.dbf";
DROP DATAFILE "C:\APP\ORACLE\ORADATA\GRAD\DATAFILE\2M_828507.dbf";

ALTER TABLESPACE "2M_828507" DROP TEMPFILE "C:\APP\ORACLE\ORADATA\GRAD\DATAFILE\2M_828507.dbf";

DROP TEMPFILE "C:\APP\ORACLE\ORADATA\GRAD\DATAFILE\2M_828507.dbf";

ALTER DATABASE TEMPFILE "C:\APP\ORACLE\ORADATA\GRAD\DATAFILE\2M_828507.dbf" DROP INCLUDING DATAFILES;
