CREATE OR REPLACE TRIGGER t
 BEFORE
 INSERT OR
 UPDATE OF salary,  emp_no OR
 DELETE
 ON employee
BEGIN
 CASE
 WHEN INSERTING THEN
 DBMS_OUTPUT.PUT_LINE('Inserting');
 WHEN UPDATING('salary') THEN
 DBMS_OUTPUT.PUT_LINE('Updating salary');
 WHEN UPDATING('department_id') THEN
 DBMS_OUTPUT.PUT_LINE('Updating department ID');
 WHEN DELETING THEN
 DBMS_OUTPUT.PUT_LINE('Deleting');
 END CASE;
END;
/